# Generated by Django 4.2.3 on 2023-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('Type', models.CharField(choices=[('fru', 'Fruit'), ('veg', 'Légume'), ('leg', 'Légumineuse'), ('car', 'Simili-carne'), ('sau', 'Sauce'), ('dai', 'Simili laitier'), ('sta', 'Féculent'), ('cer', 'Céréale'), ('flo', 'Farine'), ('hel', 'Aides culinaires'), ('swe', 'Sucré'), ('oth', 'Autres')], default='oth', max_length=3)),
                ('nutriscore', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='a', max_length=1)),
                ('season', models.CharField(choices=[('win', 'Hiver'), ('fal', 'Automne'), ('spr', 'Printemps'), ('sum', 'Eté'), ('any', 'Toutes')], default='any', max_length=3)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('pub_date', models.DateTimeField()),
                ('Type', models.CharField(choices=[('ape', 'Apéritif'), ('sta', 'Entrée'), ('cou', 'Plat'), ('des', 'Déssert')], default='cou', max_length=3)),
                ('theme', models.CharField()),
                ('source', models.CharField(max_length=200)),
                ('Temps de préparation', models.DecimalField(decimal_places=1, max_digits=5)),
                ('difficulty', models.CharField(choices=[('ve', 'Très facile'), ('ee', 'Facile'), ('nn', 'Normal'), ('hh', 'Difficile'), ('vh', 'Très difficile')], default='nn', max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('ingredients', models.ManyToManyField(to='whattoeat_api.ingredient')),
                ('regimes', models.ManyToManyField(to='whattoeat_api.regime')),
            ],
        ),
    ]
