# Generated by Django 4.2.3 on 2023-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whattoeat_api', '0003_alter_receipe_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='Temps de préparation',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='Type',
            new_name='type_receipe',
        ),
    ]
